name: "Test"

on:
  push:
    branches:
      - '**'

jobs:
  sbcl:
    name: Test 1
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Lisp etc
        run: |
          sudo apt-get install -y --no-install-recommends sbcl libuv1{,-dev} wget
      - name: Test
        run: |
          set -x
          sbcl --quit --disable-debugger --eval '(sleep 123123)' &
          pid=$!
          kill -INT $pid
          echo killed
          wait $pid
          echo done
          exit 3

  sbcl:
    name: Test 2
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Install Lisp etc
        run: |
          sudo apt-get install -y --no-install-recommends sbcl libuv1{,-dev} wget
      - name: Test
        run: |
          set -x
          file $(which sbcl)
          xxd $(which sbcl) | head
          sbcl --quit --disable-debugger --eval '(sleep 123123)' &
          pid=$!
          kill -INT $pid
          echo killed
          wait $pid
          echo done
          exit 3
