name: "Test"

on:
  push:
    branches:
      - '**'

jobs:
  examples:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Lisp etc
        run: |
          sudo apt-get install -y --no-install-recommends sbcl libuv1{,-dev} wget
      - name: Install QuickLisp
        run: |
          wget https://beta.quicklisp.org/quicklisp.lisp
          sbcl --noinform --disable-ldb --lose-on-corruption --end-runtime-options \
               --disable-debugger --no-userinit --no-sysinit --noprint \
               --load quicklisp.lisp \
               --eval '(quicklisp-quickstart:install)' \
               --quit
          mkdir -p ~/quicklisp/local-projects/
          ln -s "$PWD" ~/quicklisp/local-projects/cl-async
      - name: Run examples
        run: |
          cd examples
          for f in *.lisp; do
            if [[ f == "echo-server.lisp" ]]; then
              # Special case
              sbcl --noinform --disable-ldb --lose-on-corruption --end-runtime-options \
                   --load ~/quicklisp/setup.lisp \
                   --script "$f" &
              pid="$!"
              sleep 2
              [[ "Hello brother" == "$(echo Hello brother | nc localhost 5000)" ]]
              kill -INT "$pid"
              wait "$pid"
            else
              sbcl --noinform --disable-ldb --lose-on-corruption --end-runtime-options \
                   --load ~/quicklisp/setup.lisp \
                   --script "$f"
            fi
          done
